# Generated by Django 4.2.2 on 2023-06-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_facilitator_user_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='facilitator',
            name='title',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
