# Generated by Django 4.2.2 on 2023-06-29 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='facilitator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseFacilitator', to='school.facilitator'),
        ),
        migrations.AlterField(
            model_name='coursestudent_grade',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseCourse', to='school.course'),
        ),
        migrations.AlterField(
            model_name='coursestudent_grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseStudent', to='school.student'),
        ),
    ]
