# Generated by Django 4.2.2 on 2023-06-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_course_facilitator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent_grade',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
